[[redirects]]
    from = "/api/*"
    to = "https://logiclabsed-do-not-deploy-back-production.up.railway.app/api/:splat"
    status = 200
    force = true

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
