[build]
  base = "frontend"
  command = "npm run build"
  publish = "build"

[[redirects]]
  from = "/api/*"
  to = "https://logiclabsed-do-not-deploy-qpt4.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
